CREATE TABLE IF NOT EXISTS ANIMALITOS (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    PUBLIC_ID  VARCHAR(64) NOT NULL UNIQUE,
    NOMBRE     VARCHAR(60) NOT NULL,
    ESPECIE    VARCHAR(30) NOT NULL,
    EDAD       INT         NOT NULL
);
